### PR TITLE
Homework 2

### PR DESCRIPTION
**Pull request by Noahb930**

### CODE REVIEW

**Comment by Noahb930** [comment]
@rickyc I finished

**Comment by rickyc** [comment]
Still a few things missing.

## Homework 2
* [X] Does the application work?
* [X] Is there a HTML / CSS form to create Products?
* [X] Are the Product data saved on the server side (CloudBoost)?
* [X] When I refresh the page, do I see all the products displayed?
* [ ] Can I delete a specific product? _(You still need a way to delete the product from the UI)_
* [X] Is the code written using classes?
* [ ] Does the code make use of conditional selectors?
* [ ] Is there a map that displays all the stores location?
* [X] Does the application make use of getters / setters?
* [X] Does the application make use of constructors?
* [X] Does the application properly use const, let and vars?
* [X] Does the application use proper ES6 syntax? String interpolation, functions.
* [X] Does it follow the JavaScript code guide conventions?

_Advanced Challenges (Optional)_
* [ ] Are the classes separated into individual files?
* [ ] Is there a Store object on CloudBoost.io?
* [ ] Does the Product / Store object have nested associations?
* [ ] Can the user edit products in the store?
* [ ] Does the code use bootstrap CSS / conventions?

**Comment by rickyc** [comment]
@Noahb930 You can merge this one in.

**Comment by rickyc** [comment]
You can merge this one.

**Pull request merged**
